### ISSUE TITLE
Relational operators

### ISSUE THREAD

**Issue by andyfriesen** [andyfriesen/crux#12]
`==`, `!=`, `<`, `>`, `<=`, `>=`

Without traits, it's tricky to implement these for both numbers and strings without devolving into having them all be typed `(a, a) -> Bool`.

I eventually want to do traits, but not yet.  For now, we'll hack these into the compiler by expecting surrounding code to unify the parameters to either `Number` or `String`.

**Comment by chadaustin** [comment]
What would be wrong with copying ocaml and defining them all as (a, a) -> Bool for now?

**Comment by andyfriesen** [comment]
Good idea.  I'll do that.

**Comment by andyfriesen** [comment]
0e8260c6ec3873ada833046f5e171a347a7c97ec
