### ISSUE TITLE
syntax error: unit return type

### ISSUE THREAD

**Issue by chadaustin** [andyfriesen/crux#14]
```
export fun append(a: Array a, v: a): () {
  _unsafe_coerce(a).push(v);
}
```

results in a parse error.

**Comment by andyfriesen** [comment]
The name of the unit type is presently `Unit`, not `()`.

Should we change it to be consistent with Haskell?

**Comment by chadaustin** [comment]
I think the value and the type should have the same spelling for most unit types.  Fewer Words and all that.

We could user test this, but () means not even having to teach the word Unit.  "It's just a zero-length tuple, as in, this function has no return value."

**Comment by andyfriesen** [comment]
ok.

**Comment by chadaustin** [comment]
Pretty sure I've fixed this.
