### ISSUE TITLE
Proposal: Type-Directed Name Lookup

### ISSUE THREAD

**Issue by andyfriesen** [andyfriesen/crux#15]
Something that people really like in object oriented programming languages is the ability to write something like
```js
foo.bar()
```
and for `bar` to be looked up based on the type of `foo`.

I propose the following syntax: `a->b()` to be equivalent to `b(a)`, where `b` is looked up in the module that defines the type of `a`.

Subtleties:
* A major selling point of this syntax is to cull the number of import statements required.  Thus, this syntax will let you call functions in modules that you haven't imported.
* When we do traits, we'll have to think about how this interacts, but I think there is a good outcome to be had there.
* Type inference and TDNR are at odds, so the type of `a` must be exactly known from prior information.  This may mean that users have to write type annotations.
* We can't use the dot as the operator because it plays an active role in type inference.  `->` has pretty widespread use in other programming languages, so it has a shot at going over well.
* It is highly desirable for it to be practical for the left-side argument of `->` to be the return result of some property access, index, or function call.  ex `a->b()->c.d->e()`

**Comment by chadaustin** [comment]
At first blush, this proposal sounds great to me.

Especially that the primary selling point is to cull import statements.

**Comment by andyfriesen** [comment]
Initial support for this is merged in.  I think it has bugs!

For starters, it needs to only consider exported functions.
