### ISSUE TITLE
Type checking errors don't have files and line numbers or column numbers

### ISSUE THREAD

**Issue by chadaustin** [andyfriesen/crux#52]
I changed some things around and got an error: Constructor refers to nonexistent type "Unit"

With no location information.  I looked into adding it but this will be a bit of a substantial project -- we'll need to thread information through the type checker.

**Comment by andyfriesen** [comment]
oh I know what this one is all about.

I want to add another typechecking pass that happens before the initial type environment is built.  This pass can just validate data definitions.
